<?php
// scratch/create_acciones_formativas.php
$_SERVER['HTTP_HOST'] = 'localhost';
require_once 'includes/config.php';

$sql = "CREATE TABLE IF NOT EXISTS `acciones_formativas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `plan_id` int(11) DEFAULT NULL,
  `nivel` varchar(50) DEFAULT NULL,
  `prioridad` varchar(50) DEFAULT NULL,
  `estado` varchar(50) DEFAULT NULL,
  `destacar_web` tinyint(1) DEFAULT 0,
  `ultimas_plazas` tinyint(1) DEFAULT 0,
  `id_plataforma` varchar(100) DEFAULT NULL,
  `titulo` varchar(255) DEFAULT NULL,
  `abreviatura` varchar(100) DEFAULT NULL,
  `num_accion` int(11) DEFAULT 0,
  `duracion` int(11) DEFAULT 0,
  `p` int(11) DEFAULT 0,
  `d` int(11) DEFAULT 0,
  `t` int(11) DEFAULT 0,
  `modalidad` varchar(100) DEFAULT NULL,
  `area_tematica` varchar(255) DEFAULT NULL,
  `familia_profesional` varchar(255) DEFAULT NULL,
  `horas_teoricas` int(11) DEFAULT 0,
  `horas_practicas` int(11) DEFAULT 0,
  `dias_extra` int(11) DEFAULT 0,
  `asignacion` varchar(255) DEFAULT NULL,
  `modulo_sensib` tinyint(1) DEFAULT 0,
  `modulo_alfab` tinyint(1) DEFAULT 0,
  `encuesta_post` tinyint(1) DEFAULT 0,
  `dur_int_empresas` varchar(50) DEFAULT NULL,
  `dur_emprendimiento` varchar(50) DEFAULT NULL,
  `objetivos` text DEFAULT NULL,
  `objetivos_especificos` text DEFAULT NULL,
  `contenidos` text DEFAULT NULL,
  `contenidos_breves` text DEFAULT NULL,
  `que_aprenden` text DEFAULT NULL,
  `contenidos_fes` text DEFAULT NULL,
  `recursos_accion` text DEFAULT NULL,
  `demanda_mercado` text DEFAULT NULL,
  `creado_en` datetime NOT NULL DEFAULT current_timestamp(),
  `actualizado_en` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `hay_material` tinyint(1) DEFAULT 0,
  `num_entregas` int(11) DEFAULT 0,
  `codigo_entregas` varchar(50) DEFAULT NULL,
  `num_modulos` int(11) DEFAULT 0,
  `detalle_entregas` text DEFAULT NULL,
  `manual_curso` tinyint(1) DEFAULT 0,
  `manual_sensibilizacion` tinyint(1) DEFAULT 0,
  `carpeta_clasificadora` tinyint(1) DEFAULT 0,
  `cuaderno_a4` tinyint(1) DEFAULT 0,
  `boligrafo` tinyint(1) DEFAULT 0,
  `maletin` tinyint(1) DEFAULT 0,
  `otros_materiales` tinyint(1) DEFAULT 0,
  `otros_materiales_txt` text DEFAULT NULL,
  `material_extra_info` text DEFAULT NULL,
  `notas_gestion` text DEFAULT NULL,
  `notas_ejecucion` text DEFAULT NULL,
  `notas_instalacion` text DEFAULT NULL,
  `resp_documentacion_id` int(11) DEFAULT NULL,
  `resp_seguimiento_id` int(11) DEFAULT NULL,
  `resp_dudas_id` int(11) DEFAULT NULL,
  `tutor1_id` int(11) DEFAULT NULL,
  `tutor1_activo` tinyint(4) DEFAULT 0,
  `tutor2_id` int(11) DEFAULT NULL,
  `tutor2_activo` tinyint(4) DEFAULT 0,
  `mostrar_otras_consultoras` tinyint(4) DEFAULT 0,
  `alumnos_otras_consultoras` varchar(255) DEFAULT NULL,
  `teleformador_id` int(11) DEFAULT NULL,
  `id_grupo_gestion` varchar(100) DEFAULT NULL,
  `email_tutor_gestion` varchar(255) DEFAULT NULL,
  `nuestra_check` tinyint(4) DEFAULT 0,
  `prioritaria_check` tinyint(4) DEFAULT 0,
  `num_evaluaciones` int(11) DEFAULT 0,
  `recibi_material1` tinyint(4) DEFAULT 0,
  `recibi_material2` tinyint(4) DEFAULT 0,
  `eval1_check` tinyint(4) DEFAULT 0,
  `eval1_titulo` varchar(255) DEFAULT NULL,
  `eval2_check` tinyint(4) DEFAULT 0,
  `eval2_titulo` varchar(255) DEFAULT NULL,
  `eval3_check` tinyint(4) DEFAULT 0,
  `eval3_titulo` varchar(255) DEFAULT NULL,
  `eval4_check` tinyint(4) DEFAULT 0,
  `eval4_titulo` varchar(255) DEFAULT NULL,
  `supuesto_practico` varchar(255) DEFAULT NULL,
  `conexia_check` tinyint(4) DEFAULT 0,
  `cae_check` tinyint(4) DEFAULT 0,
  `edite_gestion_check` tinyint(4) DEFAULT 0,
  `nivel_gestion` int(11) DEFAULT 1,
  `paquete_gestion` varchar(100) DEFAULT NULL,
  `observaciones_gestion` text DEFAULT NULL,
  `solicitante` varchar(255) DEFAULT NULL,
  `sector` varchar(255) DEFAULT NULL,
  `proveedor` varchar(255) DEFAULT NULL,
  `catalogo` varchar(255) DEFAULT NULL,
  `consultora` varchar(255) DEFAULT NULL,
  `curso_id` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;";

try {
    $pdo->exec($sql);
    echo "Table 'acciones_formativas' created successfully in local database.\n";
} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
}
?>
