<?php
$_SERVER['HTTP_HOST'] = 'pre-gestion.grupoefp.es';
require_once __DIR__ . '/../includes/config.php';

try {
    $data = [
        'plan_id' => 7,
        'nivel' => 'Básico',
        'prioridad' => 'Media',
        'estado' => 'Programable',
        'ultimas_plazas' => 0,
        'id_plataforma' => 9,
        'titulo' => 'TEST COURSE INSERT',
        'abreviatura' => 'TEST',
        'num_accion' => 1,
        'duracion' => 60,
        'p' => 0,
        'd' => 0,
        't' => 0,
        'modalidad' => 'Teleformacion',
        'familia_profesional' => 'ADG',
        'horas_teoricas' => 0,
        'horas_practicas' => 0,
        'dias_extra' => 0,
        'asignacion' => '',
        'modulo_sensib' => 0,
        'modulo_alfab' => 0,
        'encuesta_post' => 0,
        'dur_int_empresas' => '___',
        'dur_emprendimiento' => '___',
        'objetivos' => '',
        'objetivos_especificos' => '',
        'contenidos' => '',
        'contenidos_breves' => '',
        'que_aprenden' => '',
        'contenidos_fes' => '',
        'recursos_accion' => '',
        'demanda_mercado' => '',
        'hay_material' => 0,
        'num_entregas' => 0,
        'codigo_entregas' => '',
        'num_modulos' => 0,
        'detalle_entregas' => '',
        'manual_curso' => 0,
        'manual_sensibilizacion' => 0,
        'carpeta_clasificadora' => 0,
        'cuaderno_a4' => 0,
        'boligrafo' => 0,
        'maletin' => 0,
        'otros_materiales' => 0,
        'otros_materiales_txt' => '',
        'material_extra_info' => '',
        'notas_gestion' => '',
        'notas_ejecucion' => '',
        'notas_instalacion' => '',
        'resp_documentacion_id' => null,
        'resp_seguimiento_id' => null,
        'resp_dudas_id' => null,
        'tutor1_id' => null,
        'tutor1_activo' => 0,
        'tutor2_id' => null,
        'tutor2_activo' => 0,
        'mostrar_otras_consultoras' => 0,
        'alumnos_otras_consultoras' => '',
        'teleformador_id' => null,
        'id_grupo_gestion' => '',
        'email_tutor_gestion' => '',
        'nuestra_check' => 0,
        'prioritaria_check' => 0,
        'num_evaluaciones' => 0,
        'recibi_material1' => 0,
        'recibi_material2' => 0,
        'eval1_check' => 0,
        'eval1_titulo' => '',
        'eval2_check' => 0,
        'eval2_titulo' => '',
        'eval3_check' => 0,
        'eval3_titulo' => '',
        'eval4_check' => 0,
        'eval4_titulo' => '',
        'supuesto_practico' => '',
        'conexia_check' => 0,
        'cae_check' => 0,
        'edite_gestion_check' => 0,
        'nivel_gestion' => 1,
        'paquete_gestion' => '',
        'observaciones_gestion' => 'TEST OBSERVACIONES'
    ];

    $sql = "INSERT INTO acciones_formativas (
        plan_id, nivel, prioridad, estado, ultimas_plazas, id_plataforma, 
        titulo, abreviatura, num_accion, duracion, p, d, t, modalidad, 
        familia_profesional, horas_teoricas, horas_practicas, dias_extra, asignacion, 
        modulo_sensib, modulo_alfab, encuesta_post, dur_int_empresas, dur_emprendimiento, 
        objetivos, objetivos_especificos, contenidos, contenidos_breves, que_aprenden, 
        contenidos_fes, recursos_accion, demanda_mercado,
        hay_material, num_entregas, codigo_entregas, num_modulos, detalle_entregas,
        manual_curso, manual_sensibilizacion, carpeta_clasificadora, cuaderno_a4,
        boligrafo, maletin, otros_materiales, otros_materiales_txt,
        material_extra_info, notas_gestion, notas_ejecucion,
        notas_instalacion, resp_documentacion_id, resp_seguimiento_id,
        resp_dudas_id, tutor1_id, tutor1_activo, tutor2_id,
        tutor2_activo, mostrar_otras_consultoras, alumnos_otras_consultoras,
        teleformador_id, id_grupo_gestion, email_tutor_gestion,
        nuestra_check, prioritaria_check, num_evaluaciones,
        recibi_material1, recibi_material2, eval1_check, eval1_titulo,
        eval2_check, eval2_titulo, eval3_check, eval3_titulo,
        eval4_check, eval4_titulo, supuesto_practico, conexia_check,
        cae_check, edite_gestion_check, nivel_gestion, paquete_gestion,
        observaciones_gestion
    ) VALUES (
        :plan_id, :nivel, :prioridad, :estado, :ultimas_plazas, :id_plataforma, 
        :titulo, :abreviatura, :num_accion, :duracion, :p, :d, :t, :modalidad, 
        :familia_profesional, :horas_teoricas, :horas_practicas, :dias_extra, :asignacion, 
        :modulo_sensib, :modulo_alfab, :encuesta_post, :dur_int_empresas, :dur_emprendimiento, 
        :objetivos, :objetivos_especificos, :contenidos, :contenidos_breves, :que_aprenden, 
        :contenidos_fes, :recursos_accion, :demanda_mercado,
        :hay_material, :num_entregas, :codigo_entregas, :num_modulos, :detalle_entregas,
        :manual_curso, :manual_sensibilizacion, :carpeta_clasificadora, :cuaderno_a4,
        :boligrafo, :maletin, :otros_materiales, :otros_materiales_txt,
        :material_extra_info, :notas_gestion, :notas_ejecucion,
        :notas_instalacion, :resp_documentacion_id, :resp_seguimiento_id,
        :resp_dudas_id, :tutor1_id, :tutor1_activo, :tutor2_id,
        :tutor2_activo, :mostrar_otras_consultoras, :alumnos_otras_consultoras,
        :teleformador_id, :id_grupo_gestion, :email_tutor_gestion,
        :nuestra_check, :prioritaria_check, :num_evaluaciones,
        :recibi_material1, :recibi_material2, :eval1_check, :eval1_titulo,
        :eval2_check, :eval2_titulo, :eval3_check, :eval3_titulo,
        :eval4_check, :eval4_titulo, :supuesto_practico, :conexia_check,
        :cae_check, :edite_gestion_check, :nivel_gestion, :paquete_gestion,
        :observaciones_gestion
    )";

    $stmt = $pdo->prepare($sql);
    $stmt->execute($data);
    echo "SUCCESS: Inserted record with ID: " . $pdo->lastInsertId() . "\n";
} catch (Exception $e) {
    echo "ERROR: " . $e->getMessage() . "\n";
}
